### ISSUE TITLE
Write down a simple roadmap

### ISSUE THREAD

**Issue by lootsy** [Ultraschall/ultraschall-4#1]
I want to know what are the next steps to go forward to US 4.
What should be done next? Which steps are useful?

Goal: A roadmap to decide how I can contribute (in a meaningful way).

**Comment by rstockm** [comment]
Wir hatten uns darauf geeinigt, dass wir hier ganz provinziell auf Deutsch schreiben (außer Kommentare im Code selber).
Die Planungen für die 4.0 starten erst, wenn wir die 3.2 draußen haben, sonst zerfransen wir uns nur.
Dann werden wir aber natürlich eine Roadmap erstellen.
Generelle Einschätzung: es wird schwer bis unmöglich, am Projekt wirklich intensiv mitzuwirken, wenn man nicht auch irgendwie REAPER/Ultraschall praktisch nutzt. Die Verzahnung zwischen dem, was uns REAPER vorgibt, und was wir wie ändern können lassen sich kaum dokumentieren, und wenn man es doch macht wie @mespotine ist es danach immer noch unverständlich, wenn man es nicht wirklich in der Software selber nachvollzieht.
Hört sich jetzt dumm an, ist aber ernst gemeint: der beste nächste Schritt ist: starte einen Podcast mit Ultraschall, damit man überhaupt ein Verständnis dafür entwickelt wie die vielen, vielen Komponenten überhaupt ineinander greifen.
Refactoring um das zu Vereinfachen ist hier btw. praktisch nicht möglich: wir modden nun mal existierende Software, da muss man an genau den Schraiben drehen, die einem zur Verfügung gestellt werden und kann nur sehr begrenzt eigene Schrauben bauen (auch wenn wir das zur 4.0 verstärkt versuchen werden).
Ein weiterer sinnvoller Schritt: einmal ein Architektur-Bild erstellen, wie eigentlich die ganzen Komponenten ineinandergreifen. Ich habe da einen Talk zu aufgezeichnet, der allerdings insofern schon wiederholt ist, als dass wir seitdem schon wieder 1/3 neue Tricks drauf haben/nutzen, namentlich: eigene GUI-Elemente zeichnen, Background-Skripte, FSFX-Module selbst erstellen.
Hier der Talk:
https://youtu.be/b2rVEffV0Hk
Und hier ein leider viel zu simples Schaubild daraus:
<img width="730" alt="image" src="https://user-images.githubusercontent.com/3195116/38215693-efd5d3e6-36c8-11e8-8712-744478ff1626.png">

**Comment by mespotine** [comment]
An sich gibts derzeit nur 2 Dinge, die für die 4.0er machbar sind:
 1) Team Backend
    Das ist in der Hauptsache das, was in t3 passiert, mit @heikopanjas  und Co sowie die Ultraschall-Lua-Api an der ich bastele
 2) Team Reaper-Doku
   Hier könntest Du Dich betätigen, was auch ein dankbares Feld ist, weil noch so viele weiße Lücken auf der Dokulandkarte von Reaper existieren.
  Im Speziellen wäre sowas hilfreich wie irgendwelche Settings-Dialoge öffnen(Preferences z.B.), da Optionen an/abwählen und schauen, wie und wo Du eine Änderung in den Config-Files oder in ner Projektdatei damit triggern kannst und das notieren.
Also ne Checkbox auf aus klicken, Dialog schließen/auf OK klicken und nen Diff machen, ob sich in irgendwelchen Config-files was geändert hat, welcher Eintrag sich geändert hat  und welcher Wert nun da steht. 
Dann wieder die Checkbox auf an klicken, Dialog schließen/auf OK klicken und nen Diff machen, ob sich in irgendwelchen Config-files was geändert hat, welcher Eintrag sich geändert hat und welcher Wert nun da steht. 
Also klassische Config-Files-Diff-Arbeit...
Das dann dokumentieren. Ne Auflistung in Markdownsyntax würde da  schon ausreichen.
Das ist zwar ziemlich monoton und eintönig, aber unglaublich hilfreich für das geplante 4.0er Feature, die individuell eingestellten Config-Settings auch nach nem Update zu erhalten.

**Comment by heikopanjas** [comment]
Get a room! This is what Slack is for.
